version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: home_storage
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: ["--auth", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  # Optional: Mongo Express for web-based MongoDB admin
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass      

volumes:
  mongo_data: